spring.application.name=Instagram
server.port=8080

# PostgreSQL Connection Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/insta_db
spring.datasource.username=postgres
spring.datasource.password=I N3v3r Stopp3d

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect